### PR TITLE
Updated laravel-blade scope

### PR DESCRIPTION
**Pull request by ahsankhatri**

### CODE REVIEW

**Comment by dev4dev** [comment]
where this scope `text.html.laravel-blade` comes from?

**Comment by ahsankhatri** [comment]
I'm using Build 3083 and latest [Laravel Blade Highlighter](https://packagecontrol.io/packages/Laravel%20Blade%20Highlighter) plugin shows scopes for blade files are ```text.html.laravel-blade```

screenshot at feb 15 02-33-21

**Comment by dev4dev** [comment]
It's very strange, because I don't see anything like that, and I have latest version of it

image

and it's `text.blade` in here https://github.com/Medalink/laravel-blade/blob/master/blade.sublime-syntax

**Comment by ahsankhatri** [comment]
After upgrading my sublime to latest version (3126) its showing now **text.blade text.html.blade**

**Pull request closed without merging**
