### PR TITLE
Add verbatim directive snippet

### PR DESCRIPTION
**Pull request by redgluten**
Add snippet for the [verbatim](https://laravel.com/docs/5.4/blade#displaying-data) directive

### CODE REVIEW

**Comment by luissmg** [comment]
Hi. This is already on my pull request.

**Comment by dev4dev** [comment]
Thanks for efforts, but I merged another one which already included this shortcut.

**Comment by redgluten** [comment]
Yeah I worked on it before looking at the PR list. My bad, thanks @luissmg !

**Comment by luissmg** [comment]
No problem @redgluten. We did it almost at the same time!

**Pull request closed without merging**
