### PR TITLE
Small fix and adding missing features from new 5.4 version

### PR DESCRIPTION
**Pull request by luissmg**
Small fix and adding missing features from new 5.4 version

### CODE REVIEW

**Comment by dev4dev** [comment]
Please, add info about new snippets into README file, and add extra new line at the end of snippet files

**Comment by luissmg** [comment]
I will do it in about 2 hours. I didn't notice that the files add a line at the end, sorry.

**Comment by luissmg** [comment]
@dev4dev I've done what you asked me. Please check it up to confirm.

**Comment by dev4dev** [comment]
Looks good to me, thank you.

**Pull request merged**
