### PR TITLE
Add can and can else snippets

### PR DESCRIPTION
**Pull request by redgluten**
Add `can` and `cane` snippets for the shiny new [authorization Blade directives](http://laravel.com/docs/5.1/authorization#within-blade-templates) in Laravel 5.1.11.

### CODE REVIEW

**Comment by dev4dev** [comment]
:+1:

**Comment by redgluten** [comment]
Great. :) You don’t use Github’s releases for Package Control? How is the package updated?

**Comment by dev4dev** [comment]
It updates automatically, just run Upgrade command from Cmd + Shift + p

**Comment by redgluten** [comment]
Ok cool. :+1:

**Pull request merged**
